# variable "allocated_storage" {}
# variable "db_name" {}
# variable "engine" {}
# variable "engine_version" {}
# variable "instance_class" {}
# variable "username" {}
# variable "password" {}
# variable "family" {}
# variable "kms_key_id" {}