# variable "internal" {}
# variable "subnets" {}
# variable "env" {}
# variable "project_name" {}
# variable "alb_name" {}
# variable "vpc_id" {}
# variable "sg_cidr_blocks" {}
# variable "certificate_arn" {}
# variable "target_group_arn" {}